### PR TITLE
Fixed assetLoader by using ItemMediaResolver

### PR DESCRIPTION
**Pull request by jbout**

### CODE REVIEW

**Comment by krampstudio** [comment]
It breaks the test `test/asset/LoaderTest.php` with the following message : 

```
There was 1 error:

1) oat\taoItems\test\pack\LoaderTest::testLoadingRelAsset
common_exception_InconsistentData: No data model found

/home/bertrand/dev/projects/package-parcc-ads/generis/core/data/ModelManager.php:44
/home/bertrand/dev/projects/package-parcc-ads/generis/core/kernel/classes/class.Resource.php:83
/home/bertrand/dev/projects/package-parcc-ads/generis/core/kernel/classes/class.Resource.php:277
/home/bertrand/dev/projects/package-parcc-ads/taoItems/models/classes/class.ItemsService.php:671
/home/bertrand/dev/projects/package-parcc-ads/taoItems/models/classes/media/LocalItemSource.php:177
/home/bertrand/dev/projects/package-parcc-ads/taoItems/models/classes/media/LocalItemSource.php:126
/home/bertrand/dev/projects/package-parcc-ads/taoItems/models/classes/asset/Loader.php:83
/home/bertrand/dev/projects/package-parcc-ads/taoItems/test/asset/LoaderTest.php:89

FAILURES!
Tests: 4, Assertions: 5, Errors: 1.
```

I don't know if the test is wrong or if the changes make it to fail.

**Comment by krampstudio** [comment]
The test uses a dummy resource `$item = new core_kernel_classes_Resource('foo');` and mocks the itemService, it's the reason why it fails. 

The test should either be removed or re-written ( cc @llecaque ) by mocking the resolver.

**Comment by krampstudio** [comment]
If the feature is needed, I can merge it asap and the test can be updated in another PR.

**Comment by jbout** [comment]
The asset-loader is currently broken, so it would make sense to merge it

**Pull request merged**
