### PR TITLE
Add asset type

### PR DESCRIPTION
**Pull request by ssipasseuth**
Added a generic asset file type to support extra type of documents (pdf, doc, txt, etc.)

### CODE REVIEW

**Comment by krampstudio** [comment]
Shouldn't this be the type _document_ instead of having assets of type asset ?

**Comment by ssipasseuth** [comment]
@siwane would it be an issue if we replace asset with document ?

**Comment by ssipasseuth** [comment]
Ok, so we changed the generic file name to document, please check the change.

**Comment by krampstudio** [comment]
You need to increase the version number (feature) so taoQtiItem can require it into https://github.com/oat-sa/extension-tao-itemqti/pull/803 because https://github.com/oat-sa/extension-tao-itemqti/pull/803/files#diff-c649f6fc05d48f6bccebb5a4a2959c13R251

**Comment by ssipasseuth** [comment]
Done

**Pull request merged**
