### PR TITLE
feat: use tabular CSV import

### PR DESCRIPTION
**Pull request by boajer**
Enable tabular import in the UI

https://oat-sa.atlassian.net/browse/ADF-89

### CODE REVIEW

**Review by gabrielfs7 — CHANGES_REQUESTED** [review]
We cannot forget to

- [x] Fix all broken tests
- [ ] Update composer.json if required 
- [ ] Cover all TODOs in the list if are blocker

**Review by chinnu-focaloid — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

**Review by gabrielfs7 — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

**Comment by AntonNeviarouski** [comment]
QA verified on http://tabular-adf-156-items-import.playground.kitchen.it.taocloud.org:46001/

**Pull request merged**
